SET SCHEMA APP

DROP TABLE "CD"

DROP TABLE "DVD"

DROP TABLE "MIDIAS"

create table "POO".CD
(
	CODIGO INTEGER default 0,
	FAIXA VARCHAR(50),
	DURACAO INTEGER default 0
)

create table "POO".DVD
(
	CODIGO INTEGER default 0,
	ATORES VARCHAR(50),
	PAPEL VARCHAR(30)
)

create table "POO".MIDIAS
(
	CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) primary key,
	TITULO VARCHAR(50),
	ANO INTEGER default 0,
	ARTISTA_DIRETOR_GERENERO VARCHAR(50),
	TIPO INTEGER default 0
)